- name: Marius van Niekerk
  email: marius.v.niekerk@gmail.com
  num_commits: 0
  first_commit: 2018-10-13 11:39:05
- name: Igor T. Ghisi
  email: igor.ghisi@gmail.com
  num_commits: 4
  github: igortg
  first_commit: 2018-02-26 18:09:46
- name: Aaron Meurer
  email: asmeurer@gmail.com
  num_commits: 34
  first_commit: 2017-06-23 14:44:39
  github: asmeurer
- name: Christopher J. Wright
  email: cjwright4242gh@gmail.com
  num_commits: 136
  first_commit: 2017-07-25 20:41:13
  alternate_emails:
  - cjwright4242@gmail.com
  aliases:
  - christopher
- name: Dougal J. Sutherland
  email: dougal@gmail.com
  num_commits: 1
  github: dougalsutherland
  first_commit: 2018-08-11 13:07:29
- name: Anthony Scopatz
  email: scopatz@gmail.com
  num_commits: 306
  first_commit: 2017-05-16 14:52:07
- name: Christoph Deil
  email: Deil.Christoph@gmail.com
  github: cdeil
  num_commits: 1
  first_commit: 2018-10-17 16:35:00
- name: ERGS
  email: scopatz@cec.sc.edu
  is_org: true
  github: ergs
  num_commits: 0
  first_commit: 2019-01-18 16:18:54.253827
- name: Michael Sarahan
  aliases:
  - Mike Sarahan
  email: msarahan@gmail.com
  num_commits: 6
  first_commit: 2019-05-14 21:01:12
  github: msarahan
- name: Baptiste Mouginot
  email: mouginot.baptiste@gmail.com
  github: bam241
  num_commits: 1
  first_commit: 2019-07-01 11:49:22
